import { Pool, PoolClient } from "pg";

let pool: Pool | null = null;

/**
 * Get or create a PostgreSQL connection pool
 * Uses the database connection info from SST Resource
 */
export function getDb(): Pool {
  if (!pool) {
    // @ts-ignore - Resource.StipChaserDB is generated by SST after deployment
    const { Resource } = require("sst");

    pool = new Pool({
      host: Resource.StipChaserDB.host,
      port: Resource.StipChaserDB.port,
      database: Resource.StipChaserDB.database,
      user: Resource.StipChaserDB.username,
      password: Resource.StipChaserDB.password,
      ssl: {
        rejectUnauthorized: false,
      },
      // Connection pool settings
      max: 10,
      idleTimeoutMillis: 30000,
      connectionTimeoutMillis: 10000,
    });
  }

  return pool;
}

// Alias for backward compatibility
export const getPool = getDb;

/**
 * Execute a query with automatic connection handling
 */
export async function query<T = any>(
  text: string,
  params?: any[]
): Promise<T[]> {
  const pool = getDb();
  const result = await pool.query(text, params);
  return result.rows;
}

/**
 * Execute a query and return a single row
 */
export async function queryOne<T = any>(
  text: string,
  params?: any[]
): Promise<T | null> {
  const rows = await query<T>(text, params);
  return rows.length > 0 ? rows[0] : null;
}

/**
 * Get a client from the pool for transactions
 */
export async function getClient(): Promise<PoolClient> {
  const pool = getDb();
  return await pool.connect();
}

/**
 * Close the connection pool (typically not needed in Lambda as connections are reused)
 */
export async function closePool(): Promise<void> {
  if (pool) {
    await pool.end();
    pool = null;
  }
}
