/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "DocumentsBucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "StipChaserApi": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "StipChaserDB": {
      "clusterArn": string
      "database": string
      "host": string
      "password": string
      "port": number
      "reader": string
      "secretArn": string
      "type": "sst.aws.Aurora"
      "username": string
    }
    "StipChaserUserPool": {
      "id": string
      "type": "sst.aws.CognitoUserPool"
    }
    "StipChaserVpc": {
      "type": "sst.aws.Vpc"
    }
    "StipChaserWeb": {
      "type": "sst.aws.Nextjs"
      "url": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}