/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "ConversationsTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "DealsTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "DocumentsBucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "DocumentsTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "MessagesTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "StipChaserApi": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "StipChaserWeb": {
      "type": "sst.aws.Nextjs"
      "url": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}